apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: inveniordm
  namespace: argocd
spec:
  project: invenio-project
  sources:
    - repoURL: https://inveniosoftware.github.io/helm-invenio/
      chart: invenio
      targetRevision: "0.8.1"
      plugin:
        name: argocd-vault-plugin-helm-files
        env:
          - name: HELM_VALUES_REPO
            value: "https://github.com/lpandath/inveniordm-helm-values"
          - name: HELM_VALUES_DIR
            value: "inveniordm-helm-values/inveniordm"

  destination:
    server: https://kubernetes.default.svc
    namespace: invenio

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
