host: inveniordm.cyverse.at

invenio:
  hostname: inveniordm.cyverse.at
  init: true
  demo_data: false
  # Custom image configuration for testing
  image:
    repository: ghcr.io/sharedrdm/instance
    tag: official-v13-mug
    pullPolicy: Always
  default_users:
    "admin@inveniordm.cyverse.at": <path:secrets/invenio/data/invenio-users#ADMIN_PASSWORD>
    "user01@inveniordm.cyverse.at": <path:secrets/invenio/data/invenio-users#USER01_PASSWORD>
    "user02@inveniordm.cyverse.at": <path:secrets/invenio/data/invenio-users#USER02_PASSWORD>
  extraConfig:
    SECURITY_REGISTERABLE: "false"

postgresql:
  enabled: true
  auth:
    username: "invenio"
    password: <path:secrets/invenio/data/db-invenio#USER_PASSWORD>
    postgresPassword: <path:secrets/invenio/data/db-invenio#POSTGRES_PASSWORD>
    database: "invenio"

redis:
  enabled: true
  replica:
    replicaCount: 1

rabbitmq:
  enabled: true
  auth:
    username: "invenio"
    password: <path:secrets/invenio/data/msg-invenio#RABBITMQ_PASSWORD>
  extraConfiguration: |
    default_user_tags.administrator = true
    default_user_tags.management = true

opensearch:
  enabled: true
  master:
    replicas: 1
    resources:
      requests:
        memory: 512Mi
        cpu: 20m
      limits:
        memory: 2Gi
        cpu: 1
  data:
    replicas: 1
    resources:
      requests:
        memory: 512Mi
        cpu: 20m
      limits:
        memory: 2Gi
        cpu: 1
  coordinating:
    replicas: 1
    resources:
      requests:
        memory: 512Mi
        cpu: 20m
      limits:
        memory: 2Gi
        cpu: 1
  ingest:
    replicas: 1
    resources:
      requests:
        memory: 512Mi
        cpu: 20m
      limits:
        memory: 2Gi
        cpu: 1

persistence:
  enabled: true
  access_mode: ReadWriteMany
  storage_class: "nfs-client"
  size: 10G

web:
  replicas: 1
  startupProbe:
    timeoutSeconds: 30
    failureThreshold: 10

worker:
  replicas: 1

flower:
  enabled: false
